// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi6YTe795cUpd4V3CdeapsDkXCw7NFu_Q',
    appId: '1:391632552910:web:d5bed5f6b48ecaeddea19f',
    messagingSenderId: '391632552910',
    projectId: 'too-pressing-b3fb2',
    authDomain: 'too-pressing-b3fb2.firebaseapp.com',
    storageBucket: 'too-pressing-b3fb2.firebasestorage.app',
    measurementId: 'G-B27DH4FP9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFaaRyL55iQVrnqZbwk7SgG1TqqOi0xFw',
    appId: '1:391632552910:android:efc87a41c1d40433dea19f',
    messagingSenderId: '391632552910',
    projectId: 'too-pressing-b3fb2',
    storageBucket: 'too-pressing-b3fb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0f2ApVGBMaLCusKazs2Zu58Z4zX1OoFI',
    appId: '1:391632552910:ios:84ef19bf43207a90dea19f',
    messagingSenderId: '391632552910',
    projectId: 'too-pressing-b3fb2',
    storageBucket: 'too-pressing-b3fb2.firebasestorage.app',
    androidClientId: '391632552910-le5035m2m5o2e9buq733vuduq0ee7pvb.apps.googleusercontent.com',
    iosClientId: '391632552910-rj3sui3m5fo9t00bnvofcdbi5n18tu1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.pressingToo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0f2ApVGBMaLCusKazs2Zu58Z4zX1OoFI',
    appId: '1:391632552910:ios:84ef19bf43207a90dea19f',
    messagingSenderId: '391632552910',
    projectId: 'too-pressing-b3fb2',
    storageBucket: 'too-pressing-b3fb2.firebasestorage.app',
    androidClientId: '391632552910-le5035m2m5o2e9buq733vuduq0ee7pvb.apps.googleusercontent.com',
    iosClientId: '391632552910-rj3sui3m5fo9t00bnvofcdbi5n18tu1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.pressingToo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi6YTe795cUpd4V3CdeapsDkXCw7NFu_Q',
    appId: '1:391632552910:web:42c1968389a234a0dea19f',
    messagingSenderId: '391632552910',
    projectId: 'too-pressing-b3fb2',
    authDomain: 'too-pressing-b3fb2.firebaseapp.com',
    storageBucket: 'too-pressing-b3fb2.firebasestorage.app',
    measurementId: 'G-43E22RTLQ9',
  );
}
